apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: users
  name: users
spec:
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      hostAliases:
      - ip: "127.0.0.1"
        hostnames:
        - "usersphp"
      - ip: "51.75.122.8"
        hostnames:
        - "mongo"
      - ip: "51.75.122.8"
        hostnames:
        - "postgres"
      containers:
      - name: users-nginx
        image: registry-intl.eu-central-1.aliyuncs.com/mgoup/users_nginx:prd
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - name: users-php
        image: registry-intl.eu-central-1.aliyuncs.com/mgoup/users_php:prd
        imagePullPolicy: Always
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      imagePullSecrets:
      - name: regcred
#      dnsPolicy: ClusterFirst
#      dnsConfig:
#        options:
#          - name: ndots
#            value: "1"
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
#---
#apiVersion: v1
#kind: Service
#metadata:
#  labels:
#    app: users
#  name: users
#spec:
#  ports:
#  - port: 80
#    protocol: TCP
#    targetPort: 80
#  selector:
#    app: users
#  sessionAffinity: None
---
apiVersion: v1
kind: Service
metadata:
  name: users
  namespace: dev
  labels:
    app: users
spec:
  selector:
    app: users
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP