apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: panel
  name: panel
spec:
  selector:
    matchLabels:
      app: panel
  template:
    metadata:
      labels:
        app: panel
    spec:
      containers:
      - name: panel
        image: registry-intl.eu-central-1.aliyuncs.com/mgoup/panel:dev
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          protocol: TCP
        env:
        - name: TZ
          value: "Europe/Madrid"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      imagePullSecrets:
      - name: regcred
#      dnsPolicy: ClusterFirst
#      dnsConfig:
#        options:
#          - name: ndots
#            value: "1"
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: panel
  name: panel
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: panel
  sessionAffinity: None