apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

#patchesStrategicMerge:
#- svc_postgresql.yaml
#- svc_mongodb.yaml

commonLabels:
  environment: dev

#kustomize edit set image registry-intl.eu-central-1.aliyuncs.com/mgoup/boards_php=registry-intl.eu-central-1.aliyuncs.com/mgoup/boards_php:prd-26

namespace: dev
resources:
- ../base/
- services_kusto.yaml
- secret_regcred.yaml
- deploy_front.yaml
- deploy_boards.yaml
- deploy_gateway.yaml
- deploy_notificator.yaml
- deploy_panel.yaml
- deploy_users.yaml
images:
- name: registry-intl.eu-central-1.aliyuncs.com/mgoup/boards_php
  newName: registry-intl.eu-central-1.aliyuncs.com/mgoup/boards_php
  newTag: prd-26
