apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  environment: dev

namespace: dev
bases:
- ../base/
- secret_regcred.yaml
- deploy_front.yaml
- deploy_boards.yaml
- deploy_gateway.yaml
- deploy_notificator.yaml
- deploy_panel.yaml
- deploy_users.yaml