apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  externalName: 51.75.122.8
  sessionAffinity: None
  type: ExternalName
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  externalName: 51.75.122.8
  sessionAffinity: None
  type: ExternalName
