#apiVersion: v1
#kind: Service
#metadata:
#  name: postgres
#spec:
#  externalName: 10.1.0.4
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  externalName: 10.1.0.4
  sessionAffinity: None
  type: ExternalName