apiVersion: apps/v1
kind: Deployment
metadata:
  name: flux
  namespace: flux
spec:
  template:
    spec:
      containers:
        - name: flux
          args:
            - --manifest-generation=true
            - --memcached-hostname=memcached.flux
            - --memcached-service=
            - --ssh-keygen-dir=/var/fluxd/keygen
            - --git-branch=master
            - --git-path=overlays/dev
            - --git-user=flux
            - --git-email=rubenpp@users.noreply.github.com
            - --git-url=git@gitlab.com:rubenpp/kustoflux.git
            - --git-poll-interval=1m00s
            - --manifest-generation=true
            - --k8s-allow-namespace=dev
            - --sync-garbage-collection