apiVersion: apps/v1
kind: Deployment
metadata:
  name: flux
  namespace: flux
spec:
  template:
    spec:
      containers:
        - name: flux
          args:
            - --manifest-generation=true
            - --memcached-hostname=memcached.flux
            - --memcached-service=
            - --ssh-keygen-dir=/var/fluxd/keygen
            - --git-branch=master
            - --git-path=dev
            - --git-user=flux
            - --git-email=rubenpp@users.noreply.github.com
            - --git-url=git@gitlab.com:rubenpp/fluxcdkustomize.git
            - --git-poll-interval=1m00s
            - --k8s-allow-namespace=dev
            - --sync-garbage-collection
            #garbagecollection -> recoge la basura ->  https://docs.fluxcd.io/en/1.17.0/references/garbagecollection.html#garbage-collection
            # allow namespace > namespaces donde actua flux https://docs.fluxcd.io/en/1.17.0/faq.html#can-i-restrict-the-namespaces-that-flux-can-see-or-operate-on